### ISSUE TITLE
touchpad_toggle.sh : disable only touchscreen?

### ISSUE THREAD

**Issue by bouncinglime** [ElectricRCAircraftGuy/eRCaGuy_dotfiles#7]
Firstly, thank you so much for sharing all of these useful scripts! And with such thorough documentation - wow. ^_^

Question, though, is... I'm running Ubuntu 20.04 on a Lenovo Yoga 3 Pro, which has both a touchscreen and a touchpad. However, they're both on the same input and I only occasionally have a functioning touchpad. I think it's something that's selected at boot, because if I have a mouse plugged in while I boot, I get the touchpad back (but only sometimes >_< ).

I'm happy to do without the touchscreen if it means I don't have to carry a mouse everywhere and reboot every time my touchpad stops working. Is this something that your script would handle? If so, what changes would I need to make to ensure that it doesn't disable anything about my touchpad?

For reference, here's the output of `xinput` :
```
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ ATML1000:00 03EB:8A0F                   	id=13	[slave  pointer  (2)]
⎜   ↳ Logitech B330/M330/M331                 	id=9	[slave  pointer  (2)]
⎜   ↳ Logitech Anywhere MX                    	id=10	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Power Button                            	id=6	[slave  keyboard (3)]
    ↳ Video Bus                               	id=7	[slave  keyboard (3)]
    ↳ Power Button                            	id=8	[slave  keyboard (3)]
    ↳ Lenovo EasyCamera: Lenovo EasyC         	id=11	[slave  keyboard (3)]
    ↳ Ideapad extra buttons                   	id=12	[slave  keyboard (3)]
    ↳ AT Translated Set 2 keyboard            	id=14	[slave  keyboard (3)]
```
Thank you!

**Comment by ElectricRCAircraftGuy** [comment]
> Is this something that your script would handle?

Yeah, I think so. You should be able to add a call to my script at boot via your `/etc/rc.local` file. Simply call `touchpad_toggle --off`, once you configure my script. But it's even easier than that. My script is meant to automate it for those switching the touchpad on/off a lot. I do that with my wife because I use the mouse and hate the touchpad, and she loves the touchpad and hates the mouse. We use Ctrl + Alt + P to rapidly toggle between those settings.

For you, just try `xinput --disable 4`. If that doesn't work, try IDs `13`, `9`, and `10` until you find the right one. Re-enable it with `xinput --enable 4` or whatever ID you determine to be your touchscreen. Then, you can add that command to the rc.local startup file. 

If you need my script to work you'd need to just modify the `TOUCHSCREEN_STR` line to match the text for your touchscreen above, and disable the touchpad one by setting `TOUCHPAD_STR="NONE"`.

**Comment by ElectricRCAircraftGuy** [comment]
I'm assuming my solution above worked for you, @bouncinglime ? If not, reopen this issue.
